export const ErrorConstant = Object.freeze({
  DEFAULT: {
    FAILED: 'FAILED',
  },
  TEMPLATE: {
    NOT_FOUND: 'NOT_FOUND',
  },
  AUTH: {
    INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
    UNAUTHORIZED: 'UNAUTHORIZED',
  },
  RENTOUT: {
    NOT_EXIST_RENTALNEWS: 'NOT_EXIST_RENTALNEWS',
  },
});
